# redis-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-lb
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30000
  selector:
    app: redis
